### ISSUE TITLE
Example please?

### ISSUE THREAD

**Issue by RohanAlexander** [stevenli-uoft/Toronto_BikeShare_Development#17]
May I use this as an example please?

If so, can you please fix one small thing in your bibtex file? Specifically, please wrap the R package names in two curly braces e.g. instead of:
  title = {opendatatoronto: Access the City of Toronto Open Data Portal},
it should be
  title = {{opendatatoronto: Access the City of Toronto Open Data Portal}},
Could do that for all the R packages please and then recompile the PDF please? It'll just fix the capitalization.

**Comment by stevenli-uoft** [comment]
Yes, you can use mine as an example.

I've fixed the bibtex files R package names and recompiled the PDF.
